Feat: Switch Component 제작 #23
404-DriverNotFound/frontend-b pull request #26
Opened 2021-08-02 12:28 UTC by PennyBlack2008

Switch Component 제작 및 스토리 작성

## 기능에 대한 설명
Switch Component 제작 및 스토리 작성

## Review요청
- Default값이 빨간색이라 switch활성화가 아닌 경고의 의미를 주는 것같아, issue에 없던 color를 넣어 primary색으로 바꿈.
- ``withStyles``에 아무런 스타일을 입히지 않았는 데, 지우는 것이 더 좋을지, 앞으로 수정할 여지를 남기는 게 나을지 결정을 못하고 남겨놨습니다. atomic 디자인 측면에서 어떻게 해야하나요?

## 테스트 (Optional)
Storybook으로 랜더링 확인

## REFERENCE (Optional)
[switch api](https://material-ui.com/api/switch/#props)
[switch sample](https://material-ui.com/components/switches/)

## ISSUE
close #23

2021-08-02 13:30 UTC, hyo-choi commented on src/components/atoms/Switch/Switch.tsx
> +})(MaterialSwitch);
질문하신 부분에 답변 드리는 걸 깜빡했네요! atomic 디자인은 컴포넌트를 재사용하기 위한 디자인 패턴이라 이렇게 스타일적인 디자인과 관계 없다고 보시는 게 맞습니다. 이런 부분은 나중에 스타일을 적용하고 싶을 때 쉽게 수정할 수 있으니 당장 필요하지 않은 경우 빼주시는 게 좋을 것 같아요.

2021-08-02 14:00 UTC, PennyBlack2008 commented on src/components/atoms/Switch/Switch.stories.tsx
> +  const [bool, setBool] = useState(false);
isChecked 좋은 것같습니다! 그것으로 변경하겠습니다.

2021-08-02 14:02 UTC, PennyBlack2008 commented on src/components/atoms/Switch/Switch.stories.tsx
> +    return setBool(false);
더 깔끔하고 좋은 방향인 것같습니다!

2021-08-02 14:03 UTC, PennyBlack2008 commented on src/components/atoms/Switch/Switch.tsx
> +})(MaterialSwitch);
오 감사합니다! 그렇게 하겠습니다!

2021-08-02 14:20 UTC, PennyBlack2008 commented on src/components/atoms/Switch/Switch.tsx
> +export type SwitchProps = {
확인했습니다. 꼼꼼하게 봐주셔서 감사합니다!

2021-08-02 14:21 UTC, PennyBlack2008 commented on src/components/atoms/Switch/Switch.tsx
> +  name: 'twoFactorSW',
네 그렇게 하는 게 더 깔끔해보이네요

2021-08-02 14:22 UTC, PennyBlack2008 commented on src/components/atoms/Switch/Switch.tsx
> +  color: 'default' | 'primary' | 'secondary',
그게 더 좋은 방향인 것같습니다!

2021-08-03 03:27 UTC, hyo-choi requested changes

2021-08-03 03:27 UTC, hyo-choi commented on src/components/atoms/Switch/Switch.tsx
> +})(MaterialSwitch);
이 코드 안 지워주셨네요! 지워주시고 아래 컴포넌트에서 `StyledSwitch` 대신 `MaterialSwitch` 사용해주세요~
그리고 MaterialSwitch에 name props가 없어서 오류가 날 수도 있을 것 같은데, 혹시 그렇게 되면 그냥 name props는 삭제하는 방향으로 가도 될 것 같습니다. 이 부분은 한 번 고쳐보신 뒤 슬랙으로 연락주시면 그때 상의해볼게요.

2021-08-03 05:23 UTC, PennyBlack2008 commented on src/components/atoms/Switch/Switch.tsx
> +})(MaterialSwitch);
MaterialSwitch에 name props 없어도 잘 작동합니다! Storybook에서 실행시키고, 개발자 도구에서 `<input class="PrivateSwitchBase-input-8 MuiSwitch-input" name="2FAswitch" type="checkbox" value="">` 으로 name이 잘 들어오는 것 확인했습니다. Hyochoi님께서 저번에 말씀해주신 Switch가 input속성을 가지고 있는 것같다는 말씀이 맞는 것같습니다!

2021-08-03 05:39 UTC, hyo-choi commented on src/components/atoms/Switch/Switch.tsx
> +})(MaterialSwitch);
오 없어도 잘 되는군요 ㅎㅎ 좋습니당 👍👍👍

2021-08-03 05:39 UTC, hyo-choi approved these changes
변경사항 모두 확인했습니다! 고생하셨습니다~

2021-08-03 05:40 UTC, merged