Feat: Menu Component 제작
404-DriverNotFound/frontend-b pull request #34
Opened 2021-08-04 14:34 UTC by PennyBlack2008

## 기능에 대한 설명
Menu Component 제작 및 스토리 작성

## 테스트 (Optional)
Storybook으로 랜더링 확인

## REFERENCE (Optional)
[App-bar demos](https://material-ui.com/components/app-bar/)
[App-bar api](https://material-ui.com/api/app-bar/)
[NavLink](https://reactrouter.com/web/api/NavLink)

## ISSUE
close #21

2021-08-04 16:54 UTC, hyo-choi requested changes
불필요한 주석만 정리되면 문제 없을 것 같습니다! 늦은 시간까지 고생 많으셨습니다~!

2021-08-04 16:54 UTC, hyo-choi commented on src/components/molecules/Menu/Menu.tsx
> +/* eslint-disable no-unused-vars */
```suggestion
```
pull받아서 삭제해봤는데 없어도 문제 없는 주석이네요! 이런 주석은 안 쓰게 되었을 때 삭제해주세요.

2021-08-04 16:54 UTC, hyo-choi commented on src/components/molecules/Menu/Menu.tsx
> +            🏓 Pong Mighty
이건 변경 요청 사항은 아닌데, `<Link>` 컴포넌트를 사용해서 클릭 가능하게 하려던 건 취소하신 걸까요? 궁금해서 여쭤봅니다!

2021-08-05 01:51 UTC, PennyBlack2008 commented on src/components/molecules/Menu/Menu.tsx
> +/* eslint-disable no-unused-vars */
네 삭제하도록 하겠습니다. 제가 꼼꼼하지 못했네요 ㅎㅎ

2021-08-05 01:53 UTC, PennyBlack2008 commented on src/components/molecules/Menu/Menu.tsx
> +            🏓 Pong Mighty
죄송합니다, 제가 깜박하고 메모를 안해놔서 놓쳤네요. 고쳐서 올리겠습니다!

2021-08-05 03:04 UTC, hyo-choi approved these changes
변경사항 반영 확인했습니다! LGTM 👍

2021-08-05 03:04 UTC, merged