Feat: 2FA Digit input code 제작
404-DriverNotFound/frontend-b pull request #37
Opened 2021-08-05 15:29 UTC by PennyBlack2008

## 기능에 대한 설명
- 2FA DigitInput verifiaction code를 제작한다.
- [Slack email verification code box 디자인](https://blog.kakaocdn.net/dn/dC0G6u/btqw2mqwH84/mhLRfgjhGHsaZBPNkjFqb1/img.png)을 참고하여 제작
- 숫자 하나만 입력가능

## 테스트 (Optional)
각각 Firefox, Chrome, Safari로 Storybook으로 랜더링, 숫자 하나만 입력 확인

## REFERENCE (Optional)
[slack email code](https://blog.kakaocdn.net/dn/dC0G6u/btqw2mqwH84/mhLRfgjhGHsaZBPNkjFqb1/img.png)
[material-ui input](https://material-ui.com/api/input/)

## ISSUE
close #35

2021-08-05 16:37 UTC, hyo-choi requested changes
디자인 잘 해주신 것 같아서 형태는 안 고쳐도 될 것 같습니다! ㅎㅎ 여러 브라우저에서 직접 확인해주신 점, 상용 레퍼런스 참고까지 해주신 점이 좋았어요. border 색 이야기는 한 번 고려해주시고, 다른 리뷰사항들 간단히 수정해주시면 바로 approve할 수 있을 것 같습니다! 늦은 시간까지 고생 많으셨습니다~ 👍

2021-08-05 16:37 UTC, hyo-choi commented on src/components/atoms/DigitInput/DigitInput.stories.tsx
> +  const handleChange = (event: { target: { value: string; }; }) => {
```suggestion
  const handleChange = (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
```
이 부분은 event가 implicitly any라서 이렇게 쓰신 걸까요? 그러면 이렇게 고치는 편이 더 깔끔할 것 같습니다!

2021-08-05 16:37 UTC, hyo-choi commented on src/components/atoms/DigitInput/DigitInput.stories.tsx
> +/* eslint-disable arrow-body-style */
```suggestion
```
더이상 필요 없는 주석입니다!

2021-08-05 16:37 UTC, hyo-choi commented on src/components/atoms/DigitInput/DigitInput.tsx
> +    border: '1px solid',
이 부분은 꼭 바꿔야 하는 건 아니고 jikang님 의견을 들어보고 싶은데, border가 아예 black인 것보다는 색이 조금 연한 편이 숫자에 집중되지 않을까 싶기도 해서요. ㅎㅎ 어떻게 생각하시나요?
```suggestion
    border: '1px solid gray',
```
or
```suggestion
    border: '1px solid lightgray',
```

2021-08-06 07:50 UTC, PennyBlack2008 commented on src/components/atoms/DigitInput/DigitInput.stories.tsx
> +/* eslint-disable arrow-body-style */
확인했습니다. 수정하겠습니다!

2021-08-06 07:51 UTC, PennyBlack2008 commented on src/components/atoms/DigitInput/DigitInput.stories.tsx
> +  const handleChange = (event: { target: { value: string; }; }) => {
제가 Quick Fix를 하면서 임시적으로 두었던 type값이 그대로 있는 실수를 했습니다. 수정하겠습니다.

2021-08-06 07:53 UTC, PennyBlack2008 commented on src/components/atoms/DigitInput/DigitInput.tsx
> +    border: '1px solid',
solidgray가 더 좋은 방향인 것 같습니다. 제안 감사합니다!!

2021-08-06 08:30 UTC, hyo-choi approved these changes
변경사항 모두 확인했습니다! 고생하셨습니다 :)

2021-08-06 08:41 UTC, merged