Feat: GameOptionCard component 제작
404-DriverNotFound/frontend-b pull request #73
Opened 2021-09-02 12:40 UTC by PennyBlack2008

## 기능에 대한 설명

Game Page에서 일반 모드, 스피드 모드, 거꾸로 모드, 관전 모드를 선택할 때 사용되는 GameOptionCard component 제작했습니다.

## 테스트 (Optional)

- [x] Storybook 랜더링 확인
- [x] console 에러 없음 확인

## REFERENCE (Optional)

[Mui-Card](https://material-ui.com/components/cards/), [hover](https://crmrelease.tistory.com/89), [스타일 참고](https://img.insight.co.kr/static/2020/03/28/700/9egvwpq44e6m270krne9.jpg)

## ISSUE

close #72

2021-09-02 13:27 UTC, hyo-choi requested changes
구상한 내용에 맞춰 코드를 작성해주셨고, App 전체와 어우러지는 디자인을 해주시려 고려하신 흔적이 많이 보여서 좋았습니다. Card 컴포넌트를 활용해서 이미지까지 넣어주신 점, Grid를 적절히 활용해서 아름답게 배치해주신 점이 특히 좋았어요. ㅎㅎ
반응형 부분은 한번 이야기 나누어보고 싶어 남긴 코멘트라 꼭 고쳐주실 필요는 없고, 코드 중복 부분이 개선되면 좋을 것 같아 Request changes로 남겼습니다! 작업 고생 많으셨습니다 👍👍

2021-09-02 13:27 UTC, hyo-choi commented on src/components/molecules/GameOptionCard/GameOptionCard.tsx
> +  },
이건 필수라기보다는 한 번 고려해보면 좋겠다 싶은 부분인데요! 저희 집 모니터 해상도가 낮게 설정되어 있어서 아래 스크린샷처럼 카드들이 한 눈에 안 들어오더라고요... 스크롤을 내리면 채팅 아래 부분도 비어버리고요.

![image](https://user-images.githubusercontent.com/57004991/131847615-3b8594f9-33f8-47ad-9bbd-3d72d8bf2f38.png)
![image](https://user-images.githubusercontent.com/57004991/131848681-3a53c42e-feec-4a6a-86a4-65d27c933fd1.png)

**질문 1)** 이런 환경을 고려해서 컴포넌트 크기가 어느 정도는 반응형으로 조절되도록 하는 게 좋을까요, 아니면 그냥 고정 사이즈로 하고 넘어가는 편이 나을까요?

그리고 이건 이 컴포넌트에서 작업할 범위는 아닌 것 같긴 한데, 이 상황을 마주치고 보니 [MainTemplate의 이 부분](https://github.com/404-DriverNotFound/frontend-b/blob/32b32e342b4d80c41dfd5871654d111c1d26ddfa/src/components/templates/MainTemplate/MainTemplate.tsx#L12)에 `overflow: 'auto'` + `List에 적용했던 스크롤바 스타일` 을 넣어주는 것도 괜찮을 것 같다는 생각이 들었습니다.
**질문 2)** 전체 화면이 스크롤되게 하는 것보다는 아래처럼 각 영역이 스크롤되도록 해주면 더 깔끔하지 않을까 싶었는데 화면 한가운데에 스크롤바가 있으면 좀 이상한가 싶기도 하고... 어떻게 생각하시나요?

![image](https://user-images.githubusercontent.com/57004991/131849109-344abac2-f60b-4479-9e4d-e3fce1235bff.png)

2021-09-02 13:27 UTC, hyo-choi commented on src/components/molecules/GameOptionCard/GameOptionCard.tsx
> +  );
```suggestion
  const GameCard = ({ alt, src, title, description }) => ( // 이름은 임의로 지어봤어요
    <>
      <CardMedia
        className={classes.image}
        component="img"
        alt={alt}
        image={src}
        title={title}
      />
      <CardContent>
        <Typo className={classes.marginBottom} variant="h5">{title}</Typo>
        <Typo variant="body1">{description}</Typo>
      </CardContent>
    </>
  );
  ...
  const ClassicGame = () => <GameCard alt="..." src="..." title="..." description="..." />;
  const SpeedGame = () => <GameCard alt="..." src="..." title="..." description="..." />;
  const ReverseGame = () => <GameCard alt="..." src="..." title="..." description="..." />;
  const WatchGame = () => <GameCard alt="..." src="..." title="..." description="..." />;
```
이런 모양의 컴포넌트가 중복되고 있는데, GameOptionCard 바깥에 이런 식으로 재사용 가능한 컴포넌트를 만들어서 코드 중복을 줄여보는 건 어떨까요?

2021-09-02 13:51 UTC, PennyBlack2008 commented on src/components/molecules/GameOptionCard/GameOptionCard.tsx
> +    '&:hover': { color: '#208fea' },
넵 감사합니다!! 파레트에서 컬러뽑기가 잘된 것같습니다

2021-09-02 13:53 UTC, PennyBlack2008 commented on src/components/molecules/GameOptionCard/GameOptionCard.tsx
> +    <CardActionArea onClick={onClick} className={classes.cardActionMargin}>
CardActionArea가 있어야 전체적으로 Card에 클릭을 할 수있더라고요 ㅎㅎ

2021-09-02 14:56 UTC, PennyBlack2008 commented on src/components/molecules/GameOptionCard/GameOptionCard.tsx
> +  },
> 질문 1) 이런 환경을 고려해서 컴포넌트 크기가 어느 정도는 반응형으로 조절되도록 하는 게 좋을까요, 아니면 그냥 고정 사이즈로 하고 넘어가는 편이 나을까요?

반응형으로 최대한 해보는 것이 좋을 것같습니다. 그렇지만 이미지와 글자가 너무 깨지게 된다면, 이미지 비교를 통해 이야기를 나눠보면 좋을 것같습니다.

전체화면보다는 스크롤로 동작하도록 하는 것이 훨씬 좋은 것같습니다!

> 질문 2) 전체 화면이 스크롤되게 하는 것보다는 아래처럼 각 영역이 스크롤되도록 해주면 더 깔끔하지 않을까 싶었는데 화면 한가운데에 스크롤바가 있으면 좀 이상한가 싶기도 하고... 어떻게 생각하시나요?

반응형으로 최대한 스크롤 작업이 필요없도록 작업해본 뒤, 그렇게도 해결이 되지 않는 다면 그 때는 어쩔 수 없이 스크롤바를 적용해야할 것같습니다.

일단은 반응형으로 최대한 작업을 해보겠습니다.

2021-09-02 15:41 UTC, PennyBlack2008 commented on src/components/molecules/GameOptionCard/GameOptionCard.tsx
> +  );
오 이런 방법도 있군요 감사합니다:). 적용하고 푸쉬하겠습니다!!

2021-09-03 09:13 UTC, PennyBlack2008 commented on src/components/molecules/GameOptionCard/GameOptionCard.tsx
> +  },
9월 3일 스크럼 회의 때 Hyochoi님과 디스코드 화면 공유를 통해 해당 부분 수정했습니다!

2021-09-03 09:14 UTC, PennyBlack2008 commented on src/components/molecules/GameOptionCard/GameOptionCard.tsx
> +  );
const GameCard = ({
    alt, src, title, description,
  }: GameCardType) => (
    <>
      <CardMedia
        className={classes.image}
        component="img"
        alt={alt}
        image={src}
        title={title}
      />
      <CardContent>
        <Typo className={classes.marginBottom} variant="h5">{title}</Typo>
        <Typo variant="body1">{description}</Typo>
      </CardContent>
    </>
  );

다음과 같이 GameCard를 만들어서 수정했습니다!

2021-09-03 09:41 UTC, hyo-choi approved these changes
이야기 나누었던 부분들에 대한 변경사항 반영분, Storybook에서 반응형으로 렌더링되는 부분까지 모두 확인했습니다! 작업하시느라 정말 고생 많으셨습니다 😄👍

2021-09-03 09:47 UTC, merged