Feat: ChannelListItem 제작
404-DriverNotFound/frontend-b pull request #88
Opened 2021-09-07 11:02 UTC by PennyBlack2008

## 기능에 대한 설명

ChannelListItem 제작
- 입장한 방이면 ``unreads`` count가 보임
- ``admin``/``owner``면 채널 참가, 채널 관리 두 버튼이 보임
- skeleton UI 추가
- ``/type/Chat.ts`` 다른 브랜치에서 가져옴

### 질문
1. ``Channel`` 권한 관련 코드를 짜기 편하게 하기 위해 ``src/types/Chat.ts``에서 아무관계도 없는 ``NONE``을 추가했는 데, 이렇게 하지 말고 **FE**에서 정제한 다른 ``type``을 따로 만드는 게 나은 지 궁금합니다.
  - 또한 ``isLocked``라는 비밀번호 방인지 확인하는 ``type``을 넣었습니다. 비밀번호가 있으면 ``true``, 없으면 ``false``로 생각하고 코드를 작성했습니다.
2. ``ChannelListItem`` 가장 앞쪽에 ``updatedAt``을 넣었습니다. 나중에 업데이트 시간 순서대로 ``ChannelListItem``을 정렬하려고 하는 데, 어떻게 생각하시는 지 궁금합니다.
3. ``Buttons component``를 너무 하드코딩식으로 짰고 storybook의 코드도 너무 원시적으로 짰습니다. 이것을 개선할 때 어떻게 개선해야할 지 힌트 부탁드립니다. ㅠㅠ 뭔가 잘못되었다는 것은 알겠지만, 어떻게 개선해야할 지 혼자 고민을 너무 오래 하게 되어 @hyo-choi님의 혜안으로 보시고 알려주셨으면 좋겠습니다.
4. 그 외에도 API와 연결했을 때 미리 ``Dialog``를 연결하는 것, ``DMListItem``과의 공통적인 것을 어떻게 고려해야하는 지 궁금합니다.

## 테스트 (Optional)

- [ ] storybook 랜더링 확인
- [ ] API 구현에 맞춰 최종 완성

## REFERENCE (Optional)

[업적, 전적용 List component 제작 PR](https://github.com/404-DriverNotFound/frontend-b/pull/80/files)
[ProfileCard](https://github.com/404-DriverNotFound/frontend-b/tree/master/src/components/organisms/ProfileCard)

## ISSUE
close #85

2021-09-07 12:34 UTC, hyo-choi requested changes
작업하시느라 고생 많으셨습니다! 개인적으로 자물쇠 아이콘 넣어주신 부분이랑 Badge 위치가 정말 적절하다 느껴져서 좋았습니다. ㅎㅎ 자잘한 리뷰 사항이 많은데 부담없이 읽어주시면 감사하겠습니다! 아래는 질문 주신 부분에 대해 나름대로 생각해서 답변 작성해본 내용입니다 😄

>Channel 권한 관련 코드를 짜기 편하게 하기 위해 src/types/Chat.ts에서 아무관계도 없는 NONE을 추가했는 데, 이렇게 하지 말고 FE에서 정제한 다른 type을 따로 만드는 게 나은 지 궁금합니다.
또한 isLocked라는 비밀번호 방인지 확인하는 type을 넣었습니다. 비밀번호가 있으면 true, 없으면 false로 생각하고 코드를 작성했습니다.

- 저는 추가해주신 내용들 전부 괜찮다고 생각합니다! 어차피 지금 만들어놓은 type들은 API응답 양식을 완전히 fix하게되면 어느 정도 엎어져야 하기 때문에 ㅠㅠ 지금 상황에서는 이렇게 처리해주신 게 적절하다고 느껴집니다! 👍

> ChannelListItem 가장 앞쪽에 updatedAt을 넣었습니다. 나중에 업데이트 시간 순서대로 ChannelListItem을 정렬하려고 하는 데, 어떻게 생각하시는 지 궁금합니다.

- 이것도 좋은 것 같습니다! 그런데 updatedAt을 기준으로 정렬하고자 한다면(pagination 때문에) 백엔드에 그렇게 정렬된 응답이 오도록 구현해주라고 부탁드리고 -> 프론트엔드는 그대로 받아 쓰는 형식이 될 것 같아서 정렬하는 기능 구현 자체는 저희 쪽에서 안 해도 될 것 같아요 ㅎㅎ

> Buttons component를 너무 하드코딩식으로 짰고 storybook의 코드도 너무 원시적으로 짰습니다. 이것을 개선할 때 어떻게 개선해야할 지 힌트 부탁드립니다. ㅠㅠ 뭔가 잘못되었다는 것은 알겠지만, 어떻게 개선해야할 지 혼자 고민을 너무 오래 하게 되어 @hyo-choi님의 혜안으로 보시고 알려주셨으면 좋겠습니다.

- Button 부분은 아래에 피드백 드렸습니다!
- Story 파일의 경우 ChannelListItem 컴포넌트 자체가 props를 많이 받도록 만들어져 있기 때문에 어쩔 수 없는 부분인 것 같아요 ㅎㅎ 제 생각에는 최선의 방식으로 작성하신 것 같습니다! 다만 아래에서 리뷰한 것처럼 객체 하나를 내려주도록 만들어지면 props가 줄어들어서 (개수가 줄어드니 당연히) 조금 더 깔끔하게 보일 수는 있을 것 같네요 ㅎㅎ

> 그 외에도 API와 연결했을 때 미리 Dialog를 연결하는 것, DMListItem과의 공통적인 것을 어떻게 고려해야하는 지 궁금합니다.

- Dialog 부분은 아래에 피드백 드렸습니다!
- 공통적인 부분은 저도 ProfileListItem 구현할 때 고민이 많이 됐는데(두 개가 비슷하게 생겨서... ㅋㅋㅋㅋ) 결국 컴포넌트 하나를 제대로 만들어둔 다음에 그걸 기반으로 하나 새로 만들었던 것 같아요... 재사용할 수 있게 만들자니 모양이 애매하게 다르고 해서 ㅠㅠ 제 생각엔 ChannelListItem이 이만하면 됐다!! 싶어지면 그 때 이 컴포넌트 기반으로 살짝 수정해서 만들어주면 좋지 않을까 싶습니다... 별로 명쾌한 답은 아닌 것 같은데 일단은요! ㅎㅎ

2021-09-07 12:34 UTC, hyo-choi commented on src/components/organisms/ChannelListItem/ChannelListItem.stories.tsx
> +        isLocked
이 부분 공개채팅이라는 이름인데 isLocked가 true네요!

2021-09-07 12:34 UTC, hyo-choi commented on src/components/organisms/ChannelListItem/ChannelListItem.tsx
> +type ChannelListItemProps = ChannelType;
> 그 외에도 API와 연결했을 때 미리 Dialog를 연결하는 것,

```suggestion
type ChannelListItemProps = {
  info: ChannelType,
  setOpen: ... ,
  setDialog: ... ,
};
```
Dialog 연결은 setOpen, setDialog를 props로 내려주는 방식으로 구현하면 될 것 같아요. 그걸 고려하면 필수로 내려줘야 할 props가 많아지게 될 거라 ChannelType 객체 자체를 내려주는 편이 깔끔하지 않을까 하는 생각이 좀 들었는데, 이건 취향의 문제인 것 같기도 해서 고민되네요 ㅎㅎ 어떻게 생각하시나요? ProfileCard와 제가 만든 ListItem들([1](https://github.com/404-DriverNotFound/frontend-b/pull/79/files#diff-75971133f5e3a69cba2fdb7e5643921b4e6244ed57735652a6d4a5249d13dbf0R44-R49))([2](https://github.com/404-DriverNotFound/frontend-b/pull/80/files#diff-cec153b7b6ec907ea99e0eb427b08d3c6c20078fe4747ceb4c41432f0dab7e06R17))([3](https://github.com/404-DriverNotFound/frontend-b/pull/80/files#diff-8f1d6f876458b2e00163413ab1c09dc9c707ae174a2c2d381823847a194c7b14R19))에서는 이렇게 구현되어 있습니다! 말하고 보니 기존 컴포넌트와 방식을 통일하는 편이 일관성있을 것 같아서 좀 답이 정해져있는 물음 드리는 것 같기도 하지만요 ㅠㅠ
(+) 이렇게 바꾸려면 [이 라인](https://github.com/404-DriverNotFound/frontend-b/pull/88/files#diff-cc6eabf90c79fdfb31955f3ff46d7df05d2dee7032a6bc9685dd7c3f5735718aR89) 아래에 `const { name, role, unreads, isLocked, updatedAt } = info;` 만 한 줄 넣어줘도 지금 코드랑 호환될 것 같습니다!
(++) 라고 쓰고 보니 story 파일은 한 번 엎어야 하겠네요... **← 여기까지 확인해주신 뒤에 의견 부탁드립니다!!!**

2021-09-07 12:34 UTC, hyo-choi commented on src/components/organisms/ChannelListItem/ChannelListItem.stories.tsx
> +        name="아무나 이야기 나눠요! ADMIN 어디갔냐 빨리다시들어와"
채널명 길이 제한을 확실히 fix한 게 아니라 피드백 드리기 애매한 부분이기는 한데...! 제 노트북 해상도에서는 채널명이 이 정도 길이가 되니 줄바꿈이 들어가면서 레이아웃이 깨져버려서 ㅠㅠ 제목을 20자 이내로 줄여주시면 보기 좋을 것 같아요! 채널명 길이 제한 자체는 ChannelInfoForm 다시 작업하게 되면 그 때 의논해봅시다 ㅎㅎ 
![image](https://user-images.githubusercontent.com/57004991/132344892-2166ddbc-1250-48d2-a69a-f3c446f3c486.png)

2021-09-07 12:34 UTC, hyo-choi commented on src/components/organisms/ChannelListItem/ChannelListItem.tsx
> +        <Grid item container justifyContent="center" alignItems="center" xs={4}>
이 부분 수정해주시면 Skeleton쪽 버튼 정렬도 수정 부탁드립니다! (혹시나 해서 ㅎㅎ)

2021-09-07 13:07 UTC, PennyBlack2008 commented on src/components/organisms/ChannelListItem/ChannelListItem.tsx
> +      <Grid className={`${classes.skeletonCard} ${classes.skeleton}`} item container justifyContent="space-around" alignItems="center">
확인하고 수정했습니다! 꼼꼼한 리뷰 감사드립니다!!

2021-09-07 13:10 UTC, PennyBlack2008 commented on src/components/organisms/ChannelListItem/ChannelListItem.tsx
> +        );
switch-case문에서 return문 안적어주면 default로 가는 것으로 착각했었는 데, 제가 기본적인 swich-case문을 헷갈렸습니다. 바로 잡아주셔서 감사합니다!

2021-09-07 13:16 UTC, PennyBlack2008 commented on src/components/organisms/ChannelListItem/ChannelListItem.tsx
> +        return (<JoinButton />);
디테일하게 봐주셔서 정말 감사합니다! 이렇게 명시하면 좀 더 가독성이 올라가고 다음에 이 코드를 봤을 때, 'NONE'을 어디에 썼는 지 확인을 하는 시간을 줄일 수 있을 것같습니다!!

2021-09-07 13:56 UTC, PennyBlack2008 commented on src/types/Chat.ts
> +  role: 'OWNER' | 'ADMIN' | 'MEMBER' | 'NONE',
네 그러네요!! 이 타입을 Chat.ts파일로 옮기고 해당 suggestion처럼 수정했습니다. 감사합니다!

그리고 MembershipRole이 들어있는 이 Channel.ts는 삭제했습니다. 하나의 파일에 하나의 타입만 있어서 삭제했습니다.

제가 작업하다가 types/Channel.ts파일을 만들고 MembershipRole을 넣었었는 데, 이 파일을 삭제하는 것을 잊고 실수로 올렸습니다. 죄송합니다. 다음부터는 stage 잘 확인하고 올리겠습니다.

2021-09-07 14:03 UTC, PennyBlack2008 commented on src/components/organisms/ChannelListItem/ChannelListItem.tsx
> +        <Grid item container justifyContent="center" alignItems="center" xs={4}>
아 그러네요 ㅠㅠ 이 글을 보고 이상한 것을 알게됐습니다. flex-end로 수정했고, Skeleton 같은 경우에도 flex-end로 조정을 해주는 것이 맞았습니다! 꼼꼼하게 봐주셔서 감사합니다! 다음에는 버튼 정렬 스타일도 suggestion처럼 통일성있게 작성하겠습니다!

2021-09-07 14:09 UTC, PennyBlack2008 commented on src/components/organisms/ChannelListItem/ChannelListItem.tsx
> +  const OpenButton = () => (<Button onClick={() => {}}>Open</Button>);
너무 좋아요!! 저는 2번이 좋은 것같아요! ProfileCard와 통일성을 위해서 열심히 작성해주신 suggestion으로 적용해보겠습니다!

2021-09-07 14:13 UTC, PennyBlack2008 commented on src/components/organisms/ChannelListItem/ChannelListItem.stories.tsx
> +        isLocked
아이고 제가 어이없는 실수를 했네요ㅠㅠ 바로 잡아주셔서 감사합니다!!

2021-09-07 15:47 UTC, PennyBlack2008 commented on src/components/organisms/ChannelListItem/ChannelListItem.tsx
> +type ChannelListItemProps = ChannelType;
setOpen, setDialog를 Props에 넣어두기만 하고 FIXME로 어떻게 구현할 지 이야기를 나눠보고 Dialog, setOpen을 구현하기라고 적어두었습니다.
일단은 여기까지만 작업하고 @hyo-choi 님과의 대화를 통해 작업 더 진행하는 게 나을 것같아 이렇게 수정하겠습니다!

현재 상황에서 Dialog를 만들 때 구현이 가능한 것과 구현하지 못한 것을 제 생각나름대로 적어봤습니다.

1. 채널 관리 버튼을 눌렀을 때 Dialog
- 채널 비밀번호 수정 -> /channels/{name}/password로 구현 가능 O
- Admin 임명/재임명, Owner 양도 -> 구현 불가능 X
2. 채널 입장 버튼을 눌렀을 때 && (비밀번호가 걸린 방이었을 때 || 채널 최대 인원으로 입장 불가)
- 채널 비밀번호 입력 -> /chnnels/{name}/members로 구현 가능 O
- 채널 최대 인원 입장 불가 -> 채널 최대 인원 모르고 채널 최대 인원일 때 response도 모른다. X 
3. 해당 채널에서 Owner/Admin에게 Ban을 당했을 때
- 채널 입장 -> 채널 입장 불가 응답 받는 것을 아직 모름 X

2021-09-07 15:52 UTC, PennyBlack2008 commented on src/components/organisms/ChannelListItem/ChannelListItem.stories.tsx
> +        name="아무나 이야기 나눠요! ADMIN 어디갔냐 빨리다시들어와"
어떻게 하면 제목을 보고 내부 옵션 설정을 어떻게 했는 지 알 수 있을 까? 생각을 하다가 저렇게 됐는 데, 지금은 글자수가 더 짧고 더 나은 스토리로 바꿨습니다.
지금 수정하고 보니, 스토리를 저렇게 만든 것이 부끄럽네요 ㅠㅠ 
@hyo-choi 님께서 잘 봐주셔서 글자수를 수정하고 고민할 시간을 가지게 되어 더 가독성이 좋은 스토리로 바꿀 수 있었습니다!

<img width="1002" alt="스크린샷 2021-09-08 오전 12 50 07" src="https://user-images.githubusercontent.com/59194905/132374546-21c5e51f-35ba-4e93-bc1e-164ab81d5dc7.png">

2021-09-08 05:25 UTC, hyo-choi approved these changes
수정 요청드린 부분, 의견 여쭤본 부분 전부 수정/고려해주신 것 확인했습니다! 어제 늦은 시간까지 작업하시느라 고생 많으셨습니다 ㅎㅎ 일단 merge하고 나머지는 ChannelPage에서 API 연동하면서 마저 채워넣으면 될 것 같아요. 늘 감사합니다 😄👍

2021-09-08 05:36 UTC, merged

2021-09-08 16:24 UTC, hyo-choi commented
이 브랜치 Conflict를 로컬에서 수정했는데, 수정하고 머지하는 과정에서 스쿼시 머지 하는 걸 잊어버렸습니다 ㅜㅠ master 브랜치에 커밋 내역까지 포함되어버렸네요...
죄송합니다! 다음부터 수동 머지할 때 스쿼시 주의하겠습니다!!!! 😭

2021-09-13 10:36 UTC, PennyBlack2008 commented
아닙니다 ㅠㅠ 문제 없을 것같습니다!!