Feat: DMListItem component 제작#89
404-DriverNotFound/frontend-b pull request #91
Opened 2021-09-09 07:47 UTC by PennyBlack2008

## 기능에 대한 설명
<img width="971" alt="스크린샷 2021-09-09 오후 4 27 33" src="https://user-images.githubusercontent.com/59194905/132641916-225b0893-e74a-44d8-be22-a14e8ebb1e71.png">

**DMListItem component를 제작했습니다.** 

### 사용 가정한 API
- `GET /dmers`: 나와 DM을 나눈 유저 목록을 가져옵니다.
- `GET /dms/opposite/{name}`: 특정 유저와 나눈 DM을 가져옵니다.

### 사용한 Type
이 Type에 unreads 프로퍼티가 없어 unreads 띄어주는 기능은 넣지 않았습니다.
```
export type MessageType = {
  content: string,
  user: UserInfoType, 
  channel: RawChannelType, // Channel 프로퍼티 사용하지 않음
  id: string, // id 프로퍼티 사용하지 않음
  createdAt: Date,
}; // FIXME TEMP
```
### useStyles를 2개 사용
skeleton을 위한 useStyles를 따로 작성했습니다.

유저의 `status`를 가져오기 위해 useStyles에 `status`를 넣었는 데, 이 `status`값을 skeleton에서 사용하지 못하기에 skeleton의 useStyles를 따로 작성했습니다.

또한 `status`를 useStyles에 넣기 위해 `status`만 따로 구조분해할당해서 사용했고 나머지는 `user.avatar`처럼 객체 프로퍼티 접근했습니다. `useStyles(user.status)`는 적용이 안됐고 왜 안되는 지 아직까지 의문입니다.

### Message가 너무 길면 길이 조정
맨 처음의 사진 처럼 메시지가 너무 길면 ...을 붙여줬습니다. 글자가 50자 이상 넘으면 47자를 가져와서 ...을 붙여주는 방식으로 작동을 해놨는 데, 해상도에 따라서 3줄이 되는 경우가 있어서 @hyo-choi 님께서 한번 봐주시면 감사드리겠습니다!!

### DM 보기 버튼**만** 있습니다
DM 보기 버튼만 있습니다. DM 안보기 버튼은 고려하지 않았고 DM 삭제도 고려하지 않았습니다. 이유는 DM 안보려면 다른 채팅으로 들어가면 그만이고, DM 삭제를 하면 **BE**에서 DM을 삭제해서 상대방에게도 DM이 삭제되는 문제가 생길 것같아 이 점은 회의를 통해 정하면 좋을 것같습니다.

### Dialog Props는 넣었지만 필요 없을 것같습니다.
Avatar를 Click하면 상대방의 Profile로 이동하고, DM 보기 버튼을 누르면 오른쪽 Chat에 DM을 볼 수 있는 것을 상상했습니다.

## 테스트 (Optional)

- [x] Storybook에서 랜더링 확인

## REFERENCE (Optional)

[업적 전전용 ListItem component PR](https://github.com/404-DriverNotFound/frontend-b/pull/80)
[ChannelList](https://github.com/404-DriverNotFound/frontend-b/pull/88)

## ISSUE

close #89

2021-09-09 11:17 UTC, hyo-choi requested changes
작업 고생하셨습니다! 👍 메시지 길이가 길면 자동으로 축약시켜주는 기능이 참 좋은 것 같습니다. ㅎㅎ
아래 리뷰드린 부분에 덧붙여서, DMListItem이 전반적으로 Card 위쪽 여백이 아래쪽 여백보다 넓어 보이는데 이 부분 원인 찾아서 수정해주실 수 있을까요?
아래는 코드에 달기 애매한 리뷰사항입니다.

> DM 보기 버튼만 있습니다
DM 보기 버튼만 있습니다. DM 안보기 버튼은 고려하지 않았고 DM 삭제도 고려하지 않았습니다. 이유는 DM 안보려면 다른 채팅으로 들어가면 그만이고, DM 삭제를 하면 BE에서 DM을 삭제해서 상대방에게도 DM이 삭제되는 문제가 생길 것같아 이 점은 회의를 통해 정하면 좋을 것같습니다.

DM은 탈퇴 기능이 없다 보니 DM 닫기나 삭제 버튼은 없는 게 맞는 것 같습니다. 버튼 관련해서는 더 수정하지 않아도 될 것 같아요!

2021-09-09 11:17 UTC, hyo-choi commented on src/components/organisms/DMListItem/DMListItem.tsx
> +  const classes = useStyles({ status });
```suggestion
  const dateStr = makeDateString(createdAt);
  const classes = useStyles({ status: user.status });
```
> 또한 status를 useStyles에 넣기 위해 status만 따로 구조분해할당해서 사용했고 나머지는 user.avatar처럼 객체 프로퍼티 접근했습니다. useStyles(user.status)는 적용이 안됐고 왜 안되는 지 아직까지 의문입니다.

[이 라인](https://github.com/404-DriverNotFound/frontend-b/pull/91/files#diff-32cdbba47ef831f15b435a1c256280962c6d21efa0b89fbb9b91e7392229287eR12)에서 StyleProps를 `status`를 프로퍼티로 가지는 객체 type으로 설정했기 때문에 당연히 `user.status`만 인자로 넘겨줄 수는 없습니다. 구조분해할당을 하지 않아도 위의 suggestion처럼 작성하시면 같은 방식으로 사용하실 수 있습니다. 작성하신 type과 JS에서의 객체 할당에 대한 종합적인 이해가 필요한 부분인데, 이해가 어려우시면 [이 페이지](https://ko.javascript.info/object)의 [이 항목](https://ko.javascript.info/object#ref-311)을 보고 리마인드하시면 좋을 것 같습니다.

2021-09-09 11:17 UTC, hyo-choi commented on src/components/organisms/DMListItem/DMListItem.tsx
> +type StyleProps = { status: UserStatusType };
```suggestion
type StyleProps = { status: UserStatusType } | null;
```

> 유저의 status를 가져오기 위해 useStyles에 status를 넣었는 데, 이 status값을 skeleton에서 사용하지 못하기에 skeleton의 useStyles를 따로 작성했습니다.

useStyles의 인자가 `{ status: UserStatusType }` type으로 고정되어있기 때문입니다. 하나의 makeStyles를 이용하시려면 위 suggestion처럼 수정하시고 [이 라인](https://github.com/404-DriverNotFound/frontend-b/pull/91/files#diff-32cdbba47ef831f15b435a1c256280962c6d21efa0b89fbb9b91e7392229287eR91)에서 `useStyles()`를 쓰는 방식으로 해결할 수 있을 것 같습니다. 다만 굳이 고칠 필요는 없는 부분이라는 생각이 들어서, 수정하셔도 안 하셔도 괜찮을 것 같아요.

2021-09-10 08:47 UTC, PennyBlack2008 commented on src/components/organisms/DMListItem/DMListItem.tsx
> +  info: MessageType,
DMRoomType의 latestMessage가 존재하지 않을 때 생기는 애매한 문제 때문에 @hyo-choi 님과 슬랙으로 상의 후, 제안해주신 `export type DMRoomType = UserInfoType & { latestMessage: MessageType, unreads: number };`으로 Type 변경하여 코드 진행했습니다!

2021-09-10 08:47 UTC, PennyBlack2008 commented on src/components/organisms/DMListItem/DMListItem.tsx
> +  setDialog: (value: DialogProps) => void,
Dialog 삭제 진행했습니다!

2021-09-10 08:49 UTC, PennyBlack2008 commented on src/components/organisms/DMListItem/DMListItem.tsx
> +  };
현재는 unreads의 추가 구현으로 content의 협소해지는 공간때문에 글자수를 32자로 제한했습니다.

2021-09-10 08:52 UTC, PennyBlack2008 commented on src/components/organisms/DMListItem/DMListItem.tsx
> +  const classes = useStyles({ status });
오... 역시 해결방법이 있었군요. 제가 이것에 대한 개념이 없었습니다. 친절하게 코드와 링크로 남겨주셔서 감사합니다.

2021-09-10 09:00 UTC, PennyBlack2008 commented on src/components/organisms/DMListItem/DMListItem.tsx
> +type StyleProps = { status: UserStatusType };
오 어떻게 해야 같이 사용할 수 있을 지 많이 고민했었는 데 친절하게 알려주셔서 감사합니다. skeleton은 따로 export해서 skeleton style은 따로 두었습니다. 감사합니다!!

2021-09-10 09:06 UTC, PennyBlack2008 commented
### 리뷰에 따라 1차 수정 완료했습니다!

- 잘못 적용하고 있었던 ChannelType을 DMRoomType으로 변경했습니다. 
- latestMessage으로 user정보를 받아오는 문제를 해결하기 위해 @hyo-choi 님께서 슬랙으로 제안해주신 `export type DMRoomType = UserInfoType & { latestMessage: MessageType, unreads: number };`으로 변경했습니다.
- unreads badge를 추가했습니다.
  - content의 공간이 부족해져 문자수를 50자에서 32자로 더 제한했습니다.
- Story 중복 코드 개선

2021-09-10 10:23 UTC, hyo-choi requested changes
Storybook과 요청사항 반영해주신 부분 모두 확인했습니다! 다른 부분은 다 좋았고, 외에 사소하게 신경쓰이는 부분이 한 군데 있어서 리뷰 확인해주시면 감사하겠습니다~ 늘 고생 많으십니다! 👍

2021-09-10 10:23 UTC, hyo-choi commented on src/components/organisms/DMListItem/DMListItem.tsx
> +        <Grid item container justifyContent="center" alignItems="center" xs={1}>
![image](https://user-images.githubusercontent.com/57004991/132838189-08bb1541-b61a-4388-b556-e15d126fc277.png)
마지막 메시지가 당일에 오지 않은 경우(story에서 message의 createdAt을 `new Date()` 대신 `new Date(2020, 8, 10)` 등으로 지정하여 확인 가능) 연월일이 생략되지 않아 이렇게 여러 줄으로 표시되어 보입니다. 제 눈에는 이 경우가 좀 못생겨 보이는데 어떻게 생각하시나요? 고치려면 방법은 아래 두 가지 정도가 있을 것 같습니다!

1. 날짜가 한 줄에 표시되도록 Grid 너비를 조정
2. 당일이 아닌 경우 연월일과 시간 사이에 명시적으로 줄바꿈을 넣고+Typo의 align을 center로 지정

2021-09-10 13:51 UTC, PennyBlack2008 commented on src/components/organisms/DMListItem/DMListItem.tsx
> +        <Grid item container justifyContent="center" alignItems="center" xs={1}>
카카오톡처럼 시간 차를 계산해서 보여주는 것으로 수정했습니다. 제가 시간에 대해서 무턱대고 생각없이 `new Date()`로 남발했네요 ㅠㅠ 확인을 더 잘하겠습니다!

2021-09-10 13:59 UTC, PennyBlack2008 commented
<img width="865" alt="스크린샷 2021-09-10 오후 10 49 35" src="https://user-images.githubusercontent.com/59194905/132864017-e9028514-8ce2-4c71-9c94-a1e39e05e9ab.png">

- 메시지 날짜와 현재시간의 차를 표기로 수정했습니다
  - 날짜 차이를 알기 쉽도록 스토리 수정
- 스켈레톤 xs값 똑같이 고쳤습니다
  - 스켈레톤 xs값이 하나가 원본 컴포넌트와 다른 수치가 있어 수정했습니다
- 글자수를 또 낮췄습니다(더 늘려도 될 경우 말씀해주시면 늘리겠습니다!)
  - 한글일 경우 조금 더 부피를 차지해서 수정했습니다
  - 크롬에서 개발자 도구를 열고 창을 줄였다 늘리면 오른쪽 위에 해상도가 나오는 데, 대략 1210px 이상일 때 **DM 보기**버튼이 온전한 크기로 나와서 이 버튼을 기준으로 글자수를 테스트를 했습니다
  - 글자수를 조절할 때 코드상으로는 [여기에](https://github.com/404-DriverNotFound/frontend-b/pull/91/files#diff-32cdbba47ef831f15b435a1c256280962c6d21efa0b89fbb9b91e7392229287eR159) 23과 20의 차이가 '...'이 들어가기 위한 +3이기만 하면 됩니다.

2021-09-13 04:03 UTC, PennyBlack2008 commented
1달 넘어가면 년월일 그대로 출력하는 것으로 바꿨습니다. 이유는 단순히 1개월을 30일로 계산하면 생기는 문제점, 윤달의 변수들을 모두 고려하기 어렵기 때문입니다. 그래서 현재 상태는 이런 모습인 데, 년월일이 너무 길어서 Typo의 속성을 caption으로 바꿔야하나 고민입니다.

> 현재 사진, 년월일 모두 Typo subtitle2
<img width="747" alt="스크린샷 2021-09-13 오후 12 58 47" src="https://user-images.githubusercontent.com/59194905/133022157-78e36d6d-7138-4856-a596-b5ddf315ac89.png">

> 이렇게 수정할까요? 년월일만 Typo caption
<img width="604" alt="스크린샷 2021-09-13 오후 12 57 56" src="https://user-images.githubusercontent.com/59194905/133022255-3dac1179-d951-41af-83e9-04c4bfdc7bb2.png">

2021-09-13 04:23 UTC, hyo-choi approved these changes
수정 요청 사항 반영해주신 부분 모두 확인하였습니다! 글자 크기는 slack에서 이야기 나눈대로 subtitle2 그대로 가면 될 것 같습니다. 이런 부분까지 신경써주신 부분이 좋았네요 ㅎㅎ 작업하시느라 고생 많으셨습니다! 늘 감사합니다 😄👍

2021-09-13 04:30 UTC, PennyBlack2008 commented
리뷰해주실 때 저에게 쉽고 정확하게 전달해주시느라 고민 많이해주시는 게 느껴져서 항상 감사합니다!! @hyo-choi

2021-09-13 04:34 UTC, merged